---
title: "TripCheckR"
author: "Winston Saunders"
date: "October 26, 2014"
output: html_document
---

```{r "get_tweets"}

##This program assumes you have already run the TwitterReader.R to download a feed timeline. 
##It reads the data in teh form of a .csv 

## Get the relevnat tweet data

        if (getwd()=="/Users/winstonsaunders/Documents") {setwd("TripcheckR")}
        file_name <- "TripCheckUS20B"

        hwy20Bfull<-read.csv(paste0(file_name, ".csv"))

        ##make the date column a date
        hwy20Bfull$created<-as.Date(hwy20Bfull$created)

        ##convert data to dataframe
        hwy_df<-hwy20Bfull

```

The data pulled is from `r hwy_df$created[1]` to `r hwy_df$created[length(hwy_df$created)]`

```{r "clean"}

dim(hwy_df)

        ##Define Search Patterns
        S1 <- "Santiam Pass Summit"
        ##Get tweets with S1
        hwy_df <-hwy_df[grep(S1, hwy_df$text),]
        
        S2 <- "crash"
        ## get tweets with S2
        hwy_df <-hwy_df[grep(S2, hyw_df$text),]

##dedup the data

hwy_df<-hwy_df[!duplicated(hwy_df$created),]



## get some details on the crash from teh text string
        ##this usually will have a mile number
        
        midist<-lapply(hwy_df$text, function(x) {y<- regexpr("Mi", x)
                                                             if (y >4) substring(x,y-3,y-1)
                                                             else "NA"})
                                                            # if (y != FALSE) substring(x, y-3, y-1)})
        
        distance<-as.numeric(midist)

        direction<-lapply(hwy_df$text, function(x) {y<- regexpr("Mi", x)
                                                             if (y >4) substring(x,y+2,y+3)
                                                             else "NA"})
        hwy_df$text<-substring(hwy_df$text,7,12)
        
        direction<-as.character(direction)

        hwy_df$created<-as.Date(hwy_df$created)

        ##bind new columns
        plotdata<-cbind(hwy_df, distance, direction )    
        ##reduce dimensions
        plotdata<-plotdata[,c(6,18,19)]
        ##filter for complete cases
        plotdata<-plotdata[complete.cases(plotdata), ]


```

You have `r dim(plotdata)[1]` complete cases meeting the search criteria 

```{r "plot_the_data"}


##timeline(plotdata)

rangeYM<- c(plotdata$created[length(plotdata$created)], plotdata$created[1])
```

```{r}
rangeYM

plot(NA,ylim=c(-1,1),xlim=rangeYM,ann=FALSE,axes=FALSE)
abline(h=0,lwd=2,col="#5B7FA3")

ypts <- rep_len(c(-1,1), length.out=nrow(plotdata))
y0pts = rep_len(0, length.out=nrow(plotdata))
txtpts <- rep_len(c(1,3), length.out=nrow(plotdata))
ylblpts <- rep_len(c(-.9,.9, -.7, .7, -.5, .5), length.out=nrow(plotdata))
lblpts <- rep_len(c(3,1), length.out=nrow(plotdata))
segments(as.Date(plotdata$created),y0pts,as.Date(plotdata$created),1,col="gray80")

axis.Date(
 1,
 at=seq.Date(rangeYM[1],rangeYM[2],by="month"),
 format="%Y-%m",
 cex.axis=0.6,
 pos=0,
 lwd=0,
 lwd.tick=2,
 col="#5B7FA3",
 font=2
)

points(plotdata$created,y=ypts, pch="-", cex=1.5, col="#5B7FA3")
par(xpd=NA)
text(
  plotdata$created, y=ylblpts,
  labels=plotdata$text, cex=0.5, pos=lblpts, srt=90
)
par(xpd=FALSE)


```